## Clean extraneous variables generated by regridding from soil order weights
# Catherine Ledna, 10/13/18

SOIL=( "Rock" "ShiftingSand" )
WD="/Volumes/cmip5_soils/regridcmip5soildata/soil-wts"

for SO in ${SOIL[@]}; do 
   cdo splitvar ${WD}/${SO}_regrid.nc ${WD}/${SO}-
   mv ${WD}/${SO}-${SO}.nc ${WD}/${SO}_regrid.nc
done