## Clean extraneous variables generated by regridding from soil order weights
# Catherine Ledna, 10/13/18

SOIL=( "Gelisol" "Histosol" "Spodosol" "Andisol" "Oxisol" "Vertisol" "Aridisol" "Ultisol" "Mollisol" "Alfisol" "Inceptisol" "Entisol" )
WD="/Volumes/cmip5_soils/Scripts_Catherine/BashScripts/LandNoIceArea/test/soil-wts"

for SO in ${SOIL[@]}; do 
   cdo splitvar ${WD}/${SO}_regrid.nc ${WD}/${SO}-
   mv ${WD}/${SO}-${SO}.nc ${WD}/${SO}_regrid.nc
done